### ISSUE TITLE
这是做什么的？

### ISSUE THREAD

**Issue by erquren** [Ahackerl/anpy#1]

**Comment by Ahackerl** [comment]
用python写安卓app

**Comment by erquren** [comment]
> 用python写安卓app
有示例代码吗？

**Comment by Ahackerl** [comment]
项目就是示例代码，还没完善，不过已经可以简单的使用python语法了

**Comment by Ahackerl** [comment]
> > 用python写安卓app
> > 有示例代码吗？

项目就是示例代码，还没完善，不过已经可以简单的使用python语法了

**Comment by Ahackerl** [comment]
。

**Comment by 052600Lv** [comment]
我想请问一下那个轰炸软件我下载解压全是文件吗？没有软件呢需要怎么做呢
